### ISSUE TITLE
This could be added as an environment variable

### ISSUE THREAD

**Issue by jgmuchiri** [Lambda-School-Labs/foster-together-fe#23]
https://github.com/Lambda-School-Labs/foster-together-fe/blob/f84bb77f97e82a1695f676b51844b7a496359c78/src/Auth/axiosWithBaseUrl.js#L4

**Comment by jgmuchiri** [comment]
Also
 https://github.com/Lambda-School-Labs/foster-together-fe/blob/f84bb77f97e82a1695f676b51844b7a496359c78/src/components/AdminDash/AdminDashboard.js#L20

and 
https://github.com/Lambda-School-Labs/foster-together-fe/blob/f84bb77f97e82a1695f676b51844b7a496359c78/src/components/AdminDash/AdminDashboard.js#L30

**Comment by jgmuchiri** [comment]
And
https://github.com/Lambda-School-Labs/foster-together-fe/blob/f84bb77f97e82a1695f676b51844b7a496359c78/src/components/AdminDash/UsersProfile.js#L9

**Comment by StacyWilliams** [comment]
Is being corrected by Bianca this morning (3/5)

**Comment by bseverino** [comment]
Converted to variables in this pull request: https://github.com/Lambda-School-Labs/foster-together-fe/pull/26
