### ISSUE TITLE
Commented out code in production

### ISSUE THREAD

**Issue by jgmuchiri** [Lambda-School-Labs/foster-together-fe#24]
https://github.com/Lambda-School-Labs/foster-together-fe/blob/f84bb77f97e82a1695f676b51844b7a496359c78/src/components/AdminDash/AdminDashboard.js#L54

Re: https://lambda-school-labs.github.io/labs-engineering-standards/topics/code-quality/#cq-120-code-cleanliness

**Comment by michelangelo17** [comment]
Edited out code removed.
